image_width: 1280
image_height: 1024
camera_name: hik
camera_matrix:
  rows: 3
  cols: 3
  data: [1581.25664,    0.     ,  633.35265,
            0.     , 1585.28482,  488.93193,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.085655, 0.307063, -0.005434, -0.003034, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1583.64906,    0.     ,  630.78218,    0.     ,
            0.     , 1586.42785,  485.3274 ,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
